package io.usoamic.validateutilkt.exception

class InvalidIdError : ValidateUtilError()