package io.usoamic.validateutilkt.exception

class InvalidPrivateKeyError : ValidateUtilError()